services:
  mongo:
      image: mongo:7.0.2
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      ports:
        - 27017:27017

  mongo-express:
    image: mongo-express:1.0.0-18
    restart: always
    ports:
      - 8081:8081
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  minio:
    image: quay.io/minio/minio:RELEASE.2023-10-14T05-17-22Z
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "secret-key"
      MINIO_DEFAULT_BUCKETS: "spartan-objects"
    command: server --console-address ":9090" /data
